//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLudico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progreso
    {
        public int ProgresoId { get; set; }
        public int ParticipanteId { get; set; }
        public int TemaId { get; set; }
        public string EstadoProgreso { get; set; }
        public Nullable<int> EjercicioId { get; set; }
    
        public virtual Ejercicio Ejercicio { get; set; }
        public virtual Participante Participante { get; set; }
        public virtual Tema Tema { get; set; }
    }
}
